[book]
title = "AWS SAA-C03 한국어 스터디북"
authors = ["Codex"]
description = "AWS Solutions Architect Associate(SAA-C03) 시험 대비용 한국어 스터디북"
language = "ko"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/IanToo2/certification-study"
site-url = "/certification-study/"
additional-css = ["theme/custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/ui-enhancements.js"]

[output.html.print]
enable = true
page-break = true
